# permissions for end users to edit eips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eip-editor-role
rules:
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips/status
  verbs:
  - get
