# permissions for end users to view eips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eip-viewer-role
rules:
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips/status
  verbs:
  - get
