# permissions for end users to view fips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fip-viewer-role
rules:
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - fips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - fips/status
  verbs:
  - get
