---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips/finalizers
  verbs:
  - update
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - eips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - fips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - fips/finalizers
  verbs:
  - update
- apiGroups:
  - networking.yealink.com.networking.yealink.com
  resources:
  - fips/status
  verbs:
  - get
  - patch
  - update
